<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34341" started-at="2017-01-20T10:35:05Z" finished-at="2017-01-20T10:35:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34341" started-at="2017-01-20T10:35:05Z" finished-at="2017-01-20T10:35:40Z">
      <class name="com.example.tests.ContactModificationTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="setUp" is-config="true" duration-ms="3577" started-at="2017-01-20T13:35:05Z" finished-at="2017-01-20T13:35:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="modifySomeContact(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="modifySomeContact" duration-ms="6019" started-at="2017-01-20T13:35:09Z" data-provider="randomValidContactGenerator" finished-at="2017-01-20T13:35:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstname=contact1831823349, lastname=contact-152113235, address=contact1881322119, homephone=contact-840743851, mobilephone=, workphone=contact349080051, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact1042829185, secondaryphone=contact144433605]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [59]: ContactData [firstname=contact1831823349, lastname=contact-152113235, address=contact1881322119, homephone=contact-840743851, mobilephone=, workphone=contact349080051, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact1042829185, secondaryphone=contact144433605] != ContactData [firstname=contact1831823349 contact-15211323, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact1831823349, lastname=contact-152113235, address=contact1881322119, homephone=contact-840743851, mobilephone=, workphone=contact349080051, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact1042829185, secondaryphone=contact144433605]] but found [ContactData [firstname=contact1831823349 contact-15211323, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [59]: ContactData [firstname=contact1831823349, lastname=contact-152113235, address=contact1881322119, homephone=contact-840743851, mobilephone=, workphone=contact349080051, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact1042829185, secondaryphone=contact144433605] != ContactData [firstname=contact1831823349 contact-15211323, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact1831823349, lastname=contact-152113235, address=contact1881322119, homephone=contact-840743851, mobilephone=, workphone=contact349080051, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact1042829185, secondaryphone=contact144433605]] but found [ContactData [firstname=contact1831823349 contact-15211323, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeContact -->
        <test-method status="FAIL" signature="modifySomeContact(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="modifySomeContact" duration-ms="5943" started-at="2017-01-20T13:35:15Z" data-provider="randomValidContactGenerator" finished-at="2017-01-20T13:35:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstname=, lastname=contact-944830002, address=contact1184347458, homephone=contact1295015107, mobilephone=contact941262614, workphone=contact1990870658, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-721205162, secondaryphone=contact-969886939]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [0]: ContactData [firstname=, lastname=contact-944830002, address=contact1184347458, homephone=contact1295015107, mobilephone=contact941262614, workphone=contact1990870658, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-721205162, secondaryphone=contact-969886939] != ContactData [firstname= contact-3317855, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=, lastname=contact-944830002, address=contact1184347458, homephone=contact1295015107, mobilephone=contact941262614, workphone=contact1990870658, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-721205162, secondaryphone=contact-969886939]] but found [ContactData [firstname= contact-3317855, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [0]: ContactData [firstname=, lastname=contact-944830002, address=contact1184347458, homephone=contact1295015107, mobilephone=contact941262614, workphone=contact1990870658, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-721205162, secondaryphone=contact-969886939] != ContactData [firstname= contact-3317855, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=, lastname=contact-944830002, address=contact1184347458, homephone=contact1295015107, mobilephone=contact941262614, workphone=contact1990870658, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-721205162, secondaryphone=contact-969886939]] but found [ContactData [firstname= contact-3317855, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeContact -->
        <test-method status="FAIL" signature="modifySomeContact(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="modifySomeContact" duration-ms="6092" started-at="2017-01-20T13:35:21Z" data-provider="randomValidContactGenerator" finished-at="2017-01-20T13:35:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstname=contact-1625981785, lastname=contact1627749263, address=contact214931494, homephone=, mobilephone=contact432061090, workphone=contact-567931198, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1040869444, secondaryphone=contact390960106]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [17]: ContactData [firstname=contact-1625981785, lastname=contact1627749263, address=contact214931494, homephone=, mobilephone=contact432061090, workphone=contact-567931198, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1040869444, secondaryphone=contact390960106] != ContactData [firstname=contact-1625981785 contact162774926, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-1625981785, lastname=contact1627749263, address=contact214931494, homephone=, mobilephone=contact432061090, workphone=contact-567931198, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1040869444, secondaryphone=contact390960106]] but found [ContactData [firstname=contact-1625981785 contact162774926, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [17]: ContactData [firstname=contact-1625981785, lastname=contact1627749263, address=contact214931494, homephone=, mobilephone=contact432061090, workphone=contact-567931198, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1040869444, secondaryphone=contact390960106] != ContactData [firstname=contact-1625981785 contact162774926, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-1625981785, lastname=contact1627749263, address=contact214931494, homephone=, mobilephone=contact432061090, workphone=contact-567931198, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1040869444, secondaryphone=contact390960106]] but found [ContactData [firstname=contact-1625981785 contact162774926, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeContact -->
        <test-method status="FAIL" signature="modifySomeContact(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="modifySomeContact" duration-ms="6054" started-at="2017-01-20T13:35:27Z" data-provider="randomValidContactGenerator" finished-at="2017-01-20T13:35:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstname=contact-789690377, lastname=contact691968569, address=, homephone=contact-2122094719, mobilephone=contact-601452259, workphone=contact1866894249, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact636294116, secondaryphone=contact-1720680115]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [44]: ContactData [firstname=contact-789690377, lastname=contact691968569, address=, homephone=contact-2122094719, mobilephone=contact-601452259, workphone=contact1866894249, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact636294116, secondaryphone=contact-1720680115] != ContactData [firstname=contact-789690377 contact69196856, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-789690377, lastname=contact691968569, address=, homephone=contact-2122094719, mobilephone=contact-601452259, workphone=contact1866894249, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact636294116, secondaryphone=contact-1720680115]] but found [ContactData [firstname=contact-789690377 contact69196856, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [44]: ContactData [firstname=contact-789690377, lastname=contact691968569, address=, homephone=contact-2122094719, mobilephone=contact-601452259, workphone=contact1866894249, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact636294116, secondaryphone=contact-1720680115] != ContactData [firstname=contact-789690377 contact69196856, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-789690377, lastname=contact691968569, address=, homephone=contact-2122094719, mobilephone=contact-601452259, workphone=contact1866894249, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact636294116, secondaryphone=contact-1720680115]] but found [ContactData [firstname=contact-789690377 contact69196856, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeContact -->
        <test-method status="FAIL" signature="modifySomeContact(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="modifySomeContact" duration-ms="6239" started-at="2017-01-20T13:35:33Z" data-provider="randomValidContactGenerator" finished-at="2017-01-20T13:35:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstname=contact408847072, lastname=contact-1941337243, address=contact-1130851550, homephone=contact146597153, mobilephone=contact-331247087, workphone=contact-374310300, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact737470023, secondaryphone=contact-397282436]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [70]: ContactData [firstname=contact408847072, lastname=contact-1941337243, address=contact-1130851550, homephone=contact146597153, mobilephone=contact-331247087, workphone=contact-374310300, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact737470023, secondaryphone=contact-397282436] != ContactData [firstname=contact408847072 contact-194133724, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact408847072, lastname=contact-1941337243, address=contact-1130851550, homephone=contact146597153, mobilephone=contact-331247087, workphone=contact-374310300, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact737470023, secondaryphone=contact-397282436]] but found [ContactData [firstname=contact408847072 contact-194133724, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [70]: ContactData [firstname=contact408847072, lastname=contact-1941337243, address=contact-1130851550, homephone=contact146597153, mobilephone=contact-331247087, workphone=contact-374310300, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact737470023, secondaryphone=contact-397282436] != ContactData [firstname=contact408847072 contact-194133724, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact408847072, lastname=contact-1941337243, address=contact-1130851550, homephone=contact146597153, mobilephone=contact-331247087, workphone=contact-374310300, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact737470023, secondaryphone=contact-397282436]] but found [ContactData [firstname=contact408847072 contact-194133724, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeContact -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="tearDown" is-config="true" duration-ms="400" started-at="2017-01-20T13:35:39Z" finished-at="2017-01-20T13:35:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.ContactModificationTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
