<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="35060" started-at="2017-01-23T15:14:56Z" finished-at="2017-01-23T15:15:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="35060" started-at="2017-01-23T15:14:56Z" finished-at="2017-01-23T15:15:31Z">
      <class name="com.example.tests.ContactModificationTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="setUp" is-config="true" duration-ms="3619" started-at="2017-01-23T18:14:56Z" finished-at="2017-01-23T18:15:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="modifySomeContact(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="modifySomeContact" duration-ms="6365" started-at="2017-01-23T18:15:00Z" data-provider="randomValidContactGenerator" finished-at="2017-01-23T18:15:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstname=, lastname=contact-1741228021, address=contact-589587095, homephone=contact-669011528, mobilephone=contact354327450, workphone=contact619177266, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact828283162, secondaryphone=]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [0]: ContactData [firstname=, lastname=contact-1741228021, address=contact-589587095, homephone=contact-669011528, mobilephone=contact354327450, workphone=contact619177266, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact828283162, secondaryphone=] != ContactData [firstname= contact-1741228021, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=, lastname=contact-1741228021, address=contact-589587095, homephone=contact-669011528, mobilephone=contact354327450, workphone=contact619177266, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact828283162, secondaryphone=]] but found [ContactData [firstname= contact-1741228021, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [0]: ContactData [firstname=, lastname=contact-1741228021, address=contact-589587095, homephone=contact-669011528, mobilephone=contact354327450, workphone=contact619177266, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact828283162, secondaryphone=] != ContactData [firstname= contact-1741228021, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=, lastname=contact-1741228021, address=contact-589587095, homephone=contact-669011528, mobilephone=contact354327450, workphone=contact619177266, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact828283162, secondaryphone=]] but found [ContactData [firstname= contact-1741228021, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeContact -->
        <test-method status="FAIL" signature="modifySomeContact(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="modifySomeContact" duration-ms="6255" started-at="2017-01-23T18:15:06Z" data-provider="randomValidContactGenerator" finished-at="2017-01-23T18:15:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstname=contact723879568, lastname=contact-629191678, address=contact-2114324236, homephone=contact-2122757444, mobilephone=contact1659447436, workphone=contact901546339, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-2002338214, secondaryphone=contact2036231583]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [78]: ContactData [firstname=contact723879568, lastname=contact-629191678, address=contact-2114324236, homephone=contact-2122757444, mobilephone=contact1659447436, workphone=contact901546339, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-2002338214, secondaryphone=contact2036231583] != ContactData [firstname=contact723879568 contact-629191678, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact723879568, lastname=contact-629191678, address=contact-2114324236, homephone=contact-2122757444, mobilephone=contact1659447436, workphone=contact901546339, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-2002338214, secondaryphone=contact2036231583]] but found [ContactData [firstname=contact723879568 contact-629191678, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [78]: ContactData [firstname=contact723879568, lastname=contact-629191678, address=contact-2114324236, homephone=contact-2122757444, mobilephone=contact1659447436, workphone=contact901546339, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-2002338214, secondaryphone=contact2036231583] != ContactData [firstname=contact723879568 contact-629191678, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact723879568, lastname=contact-629191678, address=contact-2114324236, homephone=contact-2122757444, mobilephone=contact1659447436, workphone=contact901546339, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-2002338214, secondaryphone=contact2036231583]] but found [ContactData [firstname=contact723879568 contact-629191678, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeContact -->
        <test-method status="FAIL" signature="modifySomeContact(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="modifySomeContact" duration-ms="6159" started-at="2017-01-23T18:15:12Z" data-provider="randomValidContactGenerator" finished-at="2017-01-23T18:15:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstname=contact-325665618, lastname=, address=contact306788595, homephone=contact452089784, mobilephone=contact1876851365, workphone=contact2036618770, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1809099078, secondaryphone=contact1353026811]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [36]: ContactData [firstname=contact-325665618, lastname=, address=contact306788595, homephone=contact452089784, mobilephone=contact1876851365, workphone=contact2036618770, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1809099078, secondaryphone=contact1353026811] != ContactData [firstname=contact-325665618 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-325665618, lastname=, address=contact306788595, homephone=contact452089784, mobilephone=contact1876851365, workphone=contact2036618770, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1809099078, secondaryphone=contact1353026811]] but found [ContactData [firstname=contact-325665618 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [36]: ContactData [firstname=contact-325665618, lastname=, address=contact306788595, homephone=contact452089784, mobilephone=contact1876851365, workphone=contact2036618770, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1809099078, secondaryphone=contact1353026811] != ContactData [firstname=contact-325665618 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-325665618, lastname=, address=contact306788595, homephone=contact452089784, mobilephone=contact1876851365, workphone=contact2036618770, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1809099078, secondaryphone=contact1353026811]] but found [ContactData [firstname=contact-325665618 , lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeContact -->
        <test-method status="FAIL" signature="modifySomeContact(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="modifySomeContact" duration-ms="6232" started-at="2017-01-23T18:15:18Z" data-provider="randomValidContactGenerator" finished-at="2017-01-23T18:15:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstname=contact-928493325, lastname=contact-1600198552, address=contact898387245, homephone=contact-132699873, mobilephone=contact-838118901, workphone=contact2004795078, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-712252228, secondaryphone=contact-1572203512]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [49]: ContactData [firstname=contact-928493325, lastname=contact-1600198552, address=contact898387245, homephone=contact-132699873, mobilephone=contact-838118901, workphone=contact2004795078, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-712252228, secondaryphone=contact-1572203512] != ContactData [firstname=contact-928493325 contact-1600198552, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-928493325, lastname=contact-1600198552, address=contact898387245, homephone=contact-132699873, mobilephone=contact-838118901, workphone=contact2004795078, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-712252228, secondaryphone=contact-1572203512]] but found [ContactData [firstname=contact-928493325 contact-1600198552, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [49]: ContactData [firstname=contact-928493325, lastname=contact-1600198552, address=contact898387245, homephone=contact-132699873, mobilephone=contact-838118901, workphone=contact2004795078, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-712252228, secondaryphone=contact-1572203512] != ContactData [firstname=contact-928493325 contact-1600198552, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-928493325, lastname=contact-1600198552, address=contact898387245, homephone=contact-132699873, mobilephone=contact-838118901, workphone=contact2004795078, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-712252228, secondaryphone=contact-1572203512]] but found [ContactData [firstname=contact-928493325 contact-1600198552, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeContact -->
        <test-method status="FAIL" signature="modifySomeContact(com.example.tests.ContactData)[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="modifySomeContact" duration-ms="6022" started-at="2017-01-23T18:15:25Z" data-provider="randomValidContactGenerator" finished-at="2017-01-23T18:15:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ContactData [firstname=contact-111959760, lastname=contact1643959773, address=contact573242394, homephone=contact-291017077, mobilephone=contact1314277064, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1565248067, secondaryphone=contact1102568404]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Lists differ at element [10]: ContactData [firstname=contact-111959760, lastname=contact1643959773, address=contact573242394, homephone=contact-291017077, mobilephone=contact1314277064, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1565248067, secondaryphone=contact1102568404] != ContactData [firstname=contact-111959760 contact1643959773, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-111959760, lastname=contact1643959773, address=contact573242394, homephone=contact-291017077, mobilephone=contact1314277064, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1565248067, secondaryphone=contact1102568404]] but found [ContactData [firstname=contact-111959760 contact1643959773, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Lists differ at element [10]: ContactData [firstname=contact-111959760, lastname=contact1643959773, address=contact573242394, homephone=contact-291017077, mobilephone=contact1314277064, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1565248067, secondaryphone=contact1102568404] != ContactData [firstname=contact-111959760 contact1643959773, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null] expected [ContactData [firstname=contact-111959760, lastname=contact1643959773, address=contact573242394, homephone=contact-291017077, mobilephone=contact1314277064, workphone=, email1=, emaill2=, bday=5, bmonth=May, byear=1985, secondaryaddress=contact-1565248067, secondaryphone=contact1102568404]] but found [ContactData [firstname=contact-111959760 contact1643959773, lastname=null, address=null, homephone=null, mobilephone=null, workphone=null, email1=null, emaill2=null, bday=null, bmonth=null, byear=null, secondaryaddress=null, secondaryphone=null]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:551)
	at org.testng.Assert.assertEquals(Assert.java:516)
	at com.example.tests.ContactModificationTests.modifySomeContact(ContactModificationTests.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modifySomeContact -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.example.tests.ContactModificationTests@7c0e2abd]" name="tearDown" is-config="true" duration-ms="390" started-at="2017-01-23T18:15:31Z" finished-at="2017-01-23T18:15:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.example.tests.ContactModificationTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
